### ISSUE TITLE
Need some guidance

### ISSUE THREAD

**Issue by developeron29** [hergin/statechartsdemo#1]
Hi there,

First of all, Excellent app, Loved to see it work so perfectly on my android device. Thank you

Secondly, I was trying to display some statecharts(the code is in java) developed using yakindu statecharts(on my system), into my android app. 
Looking into your excellent app, I guess you've right now, used UML-Statechart-Framework-for-Java & Atom3 to achieve the same purpose of using statecharts in android. But do you have any tutorial or suggestions on how to achieve the same using yakindu. If you do, I'll be really grateful to you for any help , if you can provide.

Thank you!
Keep up the great work

**Comment by hergin** [comment]
Unfortunately, I don't have any extra resources than the ones on their web page. Sorry.

**Comment by developeron29** [comment]
Excellent, Thanks for replying. Cheers
